# Generated by Django 5.2.1 on 2025-07-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('cover', models.URLField(blank=True, max_length=1500, null=True)),
                ('book_url', models.URLField(blank=True, max_length=1500, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('publisher', models.CharField(blank=True, max_length=500, null=True)),
                ('pub_date', models.CharField(blank=True, max_length=500, null=True)),
                ('ISBN', models.CharField(max_length=500, unique=True)),
                ('page', models.CharField(blank=True, max_length=500, null=True)),
                ('size', models.CharField(blank=True, max_length=500, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('bookmark_count', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('pw', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('birth', models.CharField(blank=True, max_length=100, null=True)),
                ('genres', models.CharField(blank=True, max_length=100, null=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('max_member', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('is_public', models.CharField(choices=[('0', '공개'), ('1', '비공개')], default='0', max_length=1)),
                ('password', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reading_groups', to='bookclub.member')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub.book')),
                ('member', models.ManyToManyField(blank=True, related_name='member_reading_groups', to='bookclub.member')),
            ],
        ),
    ]
