# Generated by Django 5.2.1 on 2025-07-11 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksearch', '0001_initial'),
        ('member', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksearch.book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
    ]
