# Generated by Django 4.2.7 on 2025-07-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('booksearch', '0001_initial'),
        ('review', '0003_remove_review_file_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booksearch.book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member'),
        ),
    ]
