# Generated by Django 5.2.1 on 2025-07-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reply', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='review.review'),
        ),
    ]
