# Generated by Django 5.2.1 on 2025-07-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
