# Generated by Django 5.2.1 on 2025-07-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='murl',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
