# Generated by Django 5.2.1 on 2025-07-14 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='채팅방 이름 (예: 감성 교환독서 모임)', max_length=255)),
                ('description', models.TextField(help_text='채팅방 설명')),
                ('created_at', models.DateField(auto_now_add=True, help_text='채팅방 생성일시')),
                ('book_title', models.CharField(help_text='책 제목', max_length=255)),
                ('book_author', models.CharField(blank=True, help_text='책 저자 (옵션)', max_length=255, null=True)),
                ('current_members', models.IntegerField(default=0, help_text='현재 참여 인원')),
                ('max_members', models.IntegerField(default=10, help_text='최대 인원')),
                ('profile_image_url', models.URLField(blank=True, help_text='채팅방 프로필 이미지 URL', max_length=500, null=True)),
                ('tags', models.JSONField(default=list, help_text='꼬북태그 (JSON 배열)')),
                ('host', models.ForeignKey(blank=True, help_text='채팅방 개설자', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='게시글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='작성일')),
                ('likes_count', models.IntegerField(default=0, help_text='좋아요 수')),
                ('image', models.ImageField(blank=True, help_text='게시글 이미지', null=True, upload_to='post_images/')),
                ('author', models.ForeignKey(help_text='게시글 작성자', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='이 게시글이 속한 그룹', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='sns_feed.groupchatroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='작성일')),
                ('author', models.ForeignKey(help_text='댓글 작성자', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='이 댓글이 속한 게시글', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sns_feed.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
