# Generated by Django 5.2.1 on 2025-07-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booksearch', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('max_member', models.IntegerField(default=2)),
                ('description', models.TextField()),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('is_public', models.IntegerField(default=0)),
                ('password', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='member.member')),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booksearch.book')),
                ('member', models.ManyToManyField(blank=True, related_name='reading_groups', to='member.member')),
            ],
        ),
    ]
