# Generated by Django 5.2.1 on 2025-07-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('shareReading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='reading_groups', to='member.member'),
        ),
    ]
