# Generated by Django 5.2.1 on 2025-07-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareReading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='password',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
