# Generated by Django 5.2.1 on 2025-07-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareReading', '0002_alter_readinggroup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
