# Generated by Django 5.2.1 on 2025-07-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksearch', '0001_initial'),
        ('shareReading', '0003_alter_readinggroup_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinggroup',
            name='book_id',
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booksearch.book'),
        ),
    ]
