# Generated by Django 5.2.1 on 2025-07-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_feed', '0002_rename_group_post_group_id_remove_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sns_feed.post')),
            ],
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
