# Generated by Django 5.2.1 on 2025-07-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('sns_feed', '0004_rename_post_comment_post_id_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlike', to='member.member')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlike', to='sns_feed.post')),
            ],
            options={
                'unique_together': {('member_id', 'post_id')},
            },
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
