# Generated by Django 5.2.1 on 2025-07-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('ntcno', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('ntitle', models.CharField(max_length=1000)),
                ('ncontent', models.TextField()),
                ('nhit', models.IntegerField(default=0)),
                ('nfile', models.ImageField(blank=True, null=True, upload_to='customer')),
                ('ndate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
