# Generated by Django 5.2.1 on 2025-07-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cscenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='Member',
            new_name='member',
        ),
    ]
