# Generated by Django 5.2.1 on 2025-07-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='nfile',
            field=models.ImageField(blank=True, null=True, upload_to='notice'),
        ),
    ]
