# Generated by Django 5.2.1 on 2025-07-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscenter', '0002_alter_notice_nfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inqno', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('ictgr', models.CharField(max_length=100)),
                ('ititle', models.CharField(max_length=1000)),
                ('icontent', models.TextField()),
                ('ifile1', models.ImageField(blank=True, null=True, upload_to='inquiry')),
                ('ifile2', models.ImageField(blank=True, null=True, upload_to='inquiry')),
                ('ifile3', models.ImageField(blank=True, null=True, upload_to='inquiry')),
                ('idate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
